package com.onescale.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "users", indexes = {
    @Index(name = "idx_user_email", columnList = "email"),
    @Index(name = "idx_user_mobile", columnList = "mobile_number"),
    @Index(name = "idx_user_client_id", columnList = "client_id"),
    @Index(name = "idx_user_device_id", columnList = "device_id")
})
@EntityListeners(AuditingEntityListener.class)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // UUID generated by the backend at registration time.
    // Included in every JWT this user receives — the token endpoint requires it.
    @Column(name = "client_id", unique = true, nullable = false, length = 36)
    private String clientId;

    // Android device ID supplied by the frontend at registration / login.
    // Persisted so the backend can detect the same device across sessions.
    @Column(name = "device_id", nullable = false, length = 255)
    private String deviceId;

    // Auth-provider that was used on the frontend: GOOGLE, FACEBOOK, EMAIL, MOBILE
    @Column(name = "provider", nullable = false, length = 20)
    private String provider;

    @Column(unique = true, length = 255)
    private String email;

    @Column(name = "mobile_number", unique = true, length = 20)
    private String mobileNumber;

    @Column(name = "full_name", length = 255)
    private String fullName;

    @Column(name = "profile_picture_url", length = 500)
    private String profilePictureUrl;

    @Column(name = "is_email_verified")
    private Boolean isEmailVerified = false;

    @Column(name = "is_mobile_verified")
    private Boolean isMobileVerified = false;

    @Column(name = "is_active")
    private Boolean isActive = true;

    @Column(name = "last_login_at")
    private LocalDateTime lastLoginAt;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // clientId is auto-generated here so callers using the builder do not have to set it.
    @PrePersist
    protected void onCreate() {
        if (clientId == null) {
            clientId = UUID.randomUUID().toString();
        }
        if (isEmailVerified == null) {
            isEmailVerified = false;
        }
        if (isMobileVerified == null) {
            isMobileVerified = false;
        }
        if (isActive == null) {
            isActive = true;
        }
    }
}
